# Generated by Django 2.0.3 on 2018-03-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
    ]
