# Generated by Django 2.0.3 on 2018-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
